apiVersion: v1
kind: Pod
metadata:
  name: vision-assistant-experiment
spec:
  restartPolicy: Never

  containers:
  - name: experiment-container
    image: "registry.ferrari.snucse.org:30443/attention-x/drive-vision-assistant-experiment:latest"
    command: ["torchrun"]
    args: [ "--nproc_per_node=1", "train.py", "--cfg-path", "train_configs/drive_finetune.yaml" ]
    imagePullPolicy: Always
    resources:
      limits:
        cpu: "50"
        memory: "400Gi"
        nvidia.com/gpu: "4"
    envFrom:
      - secretRef:
            name: wandb-secret
    volumeMounts:
    - mountPath: "/data"
      name: vision-assistant-pv
  volumes:
  - name: vision-assistant-pv
    persistentVolumeClaim:
      claimName: vision-assistant-pvc