wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.17
    cli_version: 0.15.9
    framework: huggingface
    huggingface_version: 4.28.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1694519694.079748
    t:
      1:
      - 1
      - 11
      - 29
      - 41
      - 49
      - 55
      - 63
      - 105
      2:
      - 1
      - 11
      - 29
      - 41
      - 49
      - 55
      - 63
      - 105
      3:
      - 1
      - 13
      - 23
      4: 3.9.17
      5: 0.15.9
      6: 4.28.0
      8:
      - 5
